app/core/urls.py
from django.views.generic import RedirectView
from django.urls import path

from . import views

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='wallet.list')),

    path('wallets/', views.WalletListView.as_view(), name='wallet.list'),
    path('wallet/<uuid:pk>/', views.WalletDetailView.as_view(), name='wallet.read'),
    path('wallet/<uuid:pk>/consolidate/', views.WalletConsolidateView.as_view(), name='wallet.consolidate'),

    path('assets/', views.AssetListView.as_view(), name='asset.list'),
    path('asset/<uuid:pk>/', views.AssetDetailView.as_view(), name='asset.read'),

    path('transaction/<str:tx_id>', views.TransactionDetailView.as_view(), name='transaction.read'),
    path('query/tip/', views.QueryTipView.as_view(), name='query.tip'),
]

app/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('app.core.urls')),
    path('admin/', admin.site.urls),
] \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) \
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/core/models.py
import json
import uuid

from django.conf import settings
from django.db import models

from django_cardano.models import (
    AbstractMintingPolicy,
    AbstractTransaction,
    AbstractWallet,
)

from django_cardano.settings import django_cardano_settings

lovelace_unit = django_cardano_settings.LOVELACE_UNIT


class Wallet(AbstractWallet):
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)

    def __str__(self):
        return f'{self.name} (₳ {self.ada_balance})'

    @property
    def lovelace_balance(self):
        lovelace_balance = sum([utxo['Tokens'][lovelace_unit] for utxo in self.lovelace_utxos])
        return lovelace_balance if lovelace_balance else 0

    @property
    def ada_balance(self):
        return self.lovelace_balance / 1000000


class Asset(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    date_created = models.DateTimeField(auto_now_add=True)
    name = models.CharField(max_length=30)
    metadata = models.JSONField(default=dict, blank=True)
    image = models.ImageField()

    minting_policy = models.ForeignKey(
        settings.DJANGO_CARDANO_MINTING_POLICY_MODEL,
        blank=True, null=True,
        on_delete=models.PROTECT
    )
    minting_transaction = models.OneToOneField(
        settings.DJANGO_CARDANO_TRANSACTION_MODEL,
        blank=True, null=True,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.name

    @property
    def metadata_json(self):
        return json.dumps(self.metadata)

app/core/forms.py
from decimal import Decimal
from django import forms
from django.core.exceptions import ValidationError

from django_cardano.models import (
    get_minting_policy_model,
    get_wallet_model,
)
from django_cardano.validators import validate_cardano_address

MintingPolicy = get_minting_policy_model()
Wallet = get_wallet_model()

TEXT_INPUT_CLASSES = """
    mt-1 rounded-md border-gray-300 shadow-sm text-gray-700
    focus:border-green-700 focus:ring focus:ring-green-600 focus:ring-opacity-25
"""


class WalletCreateForm(forms.ModelForm):
    password = forms.CharField(
        max_length=30,
        widget=forms.PasswordInput,
    )

    class Meta:
        model = Wallet
        fields = ('name', 'password',)


class MintingPolicyCreateForm(forms.ModelForm):
    name = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    invalid_hereafter = forms.IntegerField()

    class Meta:
        model = MintingPolicy
        fields = ('name', 'password', 'invalid_hereafter',)


class TransferADAForm(forms.Form):
    address = forms.CharField(
        label='Receiving address',
        widget=forms.Textarea(attrs={
            'class': TEXT_INPUT_CLASSES,
            'placeholder': 'Paste an address...',
            'rows': 4,
        }),
        validators=(validate_cardano_address,)
    )

    quantity = forms.CharField(
        label='Amount of ADA to send',
        widget=forms.NumberInput(attrs={
            'class': TEXT_INPUT_CLASSES,
            'step': 'any',
        }),
    )

    fee = forms.CharField(
        label='Transaction fee',
        widget=forms.TextInput(attrs={
            'class': TEXT_INPUT_CLASSES + 'bg-gray-50',
            'disabled': True,
            'value': '--------',
        }),
        required=False,
    )
    spending_password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': TEXT_INPUT_CLASSES,
        }),
        required=False,
    )

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        return int(Decimal(quantity) * 1000000)


class MintNFTForm(forms.Form):
    minting_policy = forms.ModelChoiceField(
        queryset=MintingPolicy.objects.all(),
        widget=forms.Select(
            attrs={'class': TEXT_INPUT_CLASSES},
        )
    )

    payment_wallet = forms.ModelChoiceField(
        queryset=Wallet.objects.all(),
        widget=forms.Select(
            attrs={'class': TEXT_INPUT_CLASSES},
        )
    )

    destination_address = forms.CharField(
        label='NFT destination address',
        widget=forms.Textarea(attrs={
            'class': TEXT_INPUT_CLASSES,
            'placeholder': 'Paste an address...',
            'rows': 4,
        }),
        validators=(validate_cardano_address,)
    )

    fee = forms.CharField(
        label='Transaction fee',
        widget=forms.TextInput(attrs={
            'class': TEXT_INPUT_CLASSES + 'bg-gray-50',
            'disabled': True,
            'value': '--------',
        }),
        required=False,
    )

    spending_password = forms.CharField(
        label='Spending password',
        widget=forms.PasswordInput(
            attrs={'class': TEXT_INPUT_CLASSES}
        ),
        required=False,
    )

    minting_password = forms.CharField(
        label='Minting password',
        widget=forms.PasswordInput(
            attrs={'class': TEXT_INPUT_CLASSES}
        ),
        required=False,
    )


class ConsolidateTokensForm(forms.Form):
    consolidate_tokens_password = forms.CharField(widget=forms.HiddenInput)

app/core/views.py
from django.http import Http404
from django.http import JsonResponse
from django.views.generic import (
    View,
    DetailView,
    FormView,
    ListView,
)
from django.urls import reverse
from django.utils.translation import gettext as _

from django_cardano.exceptions import CardanoError, CardanoErrorType
from django_cardano.models import (
    get_transaction_model,
    get_wallet_model,
)
from django_cardano.util import CardanoUtils

from .forms import (
    ConsolidateTokensForm,
    MintNFTForm,
    TransferADAForm,
)
from .models import Asset
from .shortcuts import clean_token_asset_name

Transaction = get_transaction_model()
Wallet = get_wallet_model()


class AssetListView(ListView):
    model = Asset


class AssetDetailView(FormView):
    form_class = MintNFTForm
    template_name = 'core/asset_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['asset'] = Asset.objects.get(pk=self.kwargs['pk'])
        return context

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.transaction = None

    def form_valid(self, form):
        asset = Asset.objects.get(pk=self.kwargs['pk'])

        form_data = form.cleaned_data

        policy = form_data['minting_policy']
        payment_wallet = form_data['payment_wallet']
        to_address = form_data['destination_address']
        spending_password = form_data['spending_password']
        minting_password = form_data['minting_password']

        asset_name = clean_token_asset_name(asset.name)
        tx_metadata = {
            "721": {
                policy.policy_id: {
                    asset_name: asset.metadata
                }
            }
        }
        mint_tokens_kwargs = {
            'policy': policy,
            'quantity': 1,
            'to_address': to_address,
            'metadata': tx_metadata,
            'asset_name': asset_name,
        }

        if spending_password and minting_password:
            try:
                self.transaction = payment_wallet.mint_tokens(
                    **mint_tokens_kwargs,
                    spending_password=spending_password,
                    minting_password=minting_password,
                )
                asset.minting_transaction = self.transaction
                asset.minting_policy = policy
                asset.save()

                return super().form_valid(form)
            except CardanoError as e:
                error_field_name = None
                if e.code == CardanoErrorType.SIGNING_KEY_DECRYPTION_FAILURE:
                    error_field_name = 'spending_password'
                elif e.code == CardanoErrorType.POLICY_SIGNING_KEY_DECRYPTION_FAILURE:
                    error_field_name = 'minting_password'
                form.add_error(error_field_name, str(e))
                return self.form_invalid(form)
        else:
            try:
                transaction = payment_wallet.mint_tokens(
                    **mint_tokens_kwargs,
                    spending_password=None,
                    minting_password=None,
                )
                tx_fee = transaction.calculate_min_fee()
                return JsonResponse({'fee': tx_fee})
            except CardanoError as e:
                return JsonResponse({'error': str(e)}, status=400)

    def get_success_url(self):
        return reverse('transaction.read', kwargs={
            'tx_id': self.transaction.tx_id
        })


class WalletListView(ListView):
    model = Wallet


class WalletDetailView(FormView):
    form_class = TransferADAForm
    template_name = 'core/wallet_detail.html'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.transaction = None

    def get_success_url(self):
        return reverse('transaction.read', kwargs={
            'tx_id': self.transaction.tx_id
        })

    def form_valid(self, form):
        form_data = form.cleaned_data

        wallet = Wallet.objects.get(pk=self.kwargs['pk'])
        to_address = form_data['address']
        quantity = form_data['quantity']
        spending_password = form_data['spending_password']

        if spending_password:
            try:
                self.transaction = wallet.send_lovelace(
                    to_address=to_address,
                    quantity=quantity,
                    password=spending_password,
                )
                return super().form_valid(form)
            except CardanoError as e:
                error_field_name = None
                if e.code == CardanoErrorType.SIGNING_KEY_DECRYPTION_FAILURE:
                    error_field_name = 'spending_password'
                form.add_error(error_field_name, str(e))
                return self.form_invalid(form)
        else:
            try:
                transaction = wallet.send_lovelace(
                    to_address=to_address,
                    quantity=quantity,
                )
                tx_fee = transaction.calculate_min_fee()
                return JsonResponse({'fee': tx_fee})
            except CardanoError as e:
                return JsonResponse({'error': str(e)}, status=400)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context.update({
            'wallet': Wallet.objects.get(pk=self.kwargs['pk']),
            'consolidate_tokens_form': ConsolidateTokensForm(),
        })

        return context


class WalletConsolidateView(FormView):
    form_class = ConsolidateTokensForm

    def form_valid(self, form):
        wallet = Wallet.objects.get(pk=self.kwargs['pk'])
        try:
            transaction = wallet.consolidate_utxos(
                password=form.cleaned_data['consolidate_tokens_password']
            )
        except CardanoError as e:
            return JsonResponse({'error': str(e)}, status=400)

        transaction_url = reverse('transaction.read', kwargs={
            'tx_id': transaction.tx_id
        })
        return JsonResponse({'transaction_url': transaction_url})

    def form_invalid(self, form):
        return JsonResponse({'error': 'Invalid password'})


class TransactionDetailView(DetailView):
    model = Transaction
    template_name = 'core/transaction_detail.html'

    def get_object(self, queryset=None):
        try:
            # Get the single item from the filtered queryset
            return self.get_queryset().get(tx_id=self.kwargs.get('tx_id'))
        except Transaction.DoesNotExist:
            raise Http404(_("No transaction found matching the query"))


class QueryTipView(View):
    def get(self, request, *args, **kwargs):
        return JsonResponse(CardanoUtils.query_tip())

app/templates/core/asset_detail.html
{% extends 'base.html' %}
{% load static %}
{% load core_extras %}

{% block style %}
    {{ block.super }}

    <style>
    #mint-nft-form label:not(:first-of-type) {
        margin-top: 1.2rem;
    }

    .errorlist li {
      color: red;
      font-size: 0.875rem;
    }

    .errorlist.nonfield {
      order: 1;
      margin-top: 0.5rem;
    }

    #id_metadata {
        font-size: 0.75rem;
        color: gray;
        font-family: monospace;
    }

    #id_destination_address {
        font-size: 0.875rem;
    }

    .card-container {
      position: relative;
    }

    .card, .card-front, .card-back {
      position: absolute;
      width: 100%;
      height: 100%;
      transform-style: preserve-3d;
      transition: transform 0.5s ease;
    }

    .card-front, .card-back {
      backface-visibility: hidden;
    }

    .card-back {
      transform: rotateY(180deg);
    }
    </style>
{% endblock %}


{% block header_content %}
  <h1 class="text-3xl text-gray-900 font-semibold tracking-wide uppercase">
    {{ asset.name }}
  </h1>
{% endblock %}


{% block content %}
  <main class="mt-6">
    {% if asset.minting_transaction %}
      {% include 'core/include/minted_asset_view.html' %}
    {% else %}
      {% include 'core/include/unminted_asset_view.html' %}
    {% endif %}
  </main>
{% endblock %}

{% block body_scripts %}
  {{ block.super }}

  <script>
    var assetMetadata = JSON.parse('{{ asset.metadata_json|safe }}');
  </script>
  <script src="{% static 'js/asset_detail.js' %}"></script>
{% endblock %}

app/templates/core/asset_list.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
  {{ block.super }}

  <style>
    .grid-cell {
      background-position: center;
      background-repeat: no-repeat;
      background-size: cover;
      padding-top: 100%;
      position: relative;
      width: 100%;
    }
  </style>
{% endblock %}


{% block header_content %}
  <h1 class="text-3xl text-gray-900 font-semibold tracking-wide uppercase">
    {{ asset_list.count }} Assets
  </h1>
{% endblock %}


{% block content %}
  <div class="py-8 px-4">
    <ul class="grid gap-12 grid-cols-2 sm:grid-cols-3 md:grid-cols-4">
      {% for asset in asset_list %}
        <li class="grid-cell">
          <a
            class="hover:opacity-75"
            href="{% url 'asset.read' asset.id %}"
          >
            <img
              alt="{{ asset.name }}"
              class="absolute top-0 w-full h-full object-cover rounded-md"
              src="{{ asset.image.url }}"
            >
          </a>
          <h2 class="absolute text-gray-900 text-base text-center left-0 right-0">
            {{ asset.name }}
          </h2>

          {% if asset.minting_transaction %}
            <a
              class="
                absolute bottom-2 right-2 w-10 h-10 flex items-center justify-center
                rounded-full border-double border-4 border-gray-400 bg-gray-50 text-gray-900
                hover:bg-green-100 hover:border-gray-500
              "
              href="{% url 'transaction.read' asset.minting_transaction.tx_id %}"
            >
              <i class="fas fa-leaf text-xl"></i>
            </a>
          {% endif %}
        </li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}

app/templates/core/transaction_complete.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
  <main>
    <div class="max-w-5xl mx-auto px-4 my-6 text-center">
      <h1 class="text-3xl text-gray-900 font-semibold tracking-wide uppercase">
        Transaction Submitted
      </h1>

      <a
        class="text-sm break-all hover:underline"
        href="https://explorer.cardano-testnet.iohkdev.io/en/transaction?id={{ transaction.tx_id }}"
        target="_blank"
        rel="noopener"
      >
        {{ transaction.tx_id }}
      </a>

    </div>

  </main>
{% endblock %}

app/templates/core/transaction_detail.html
{% extends 'base.html' %}
{% load static %}

{% block header_content %}
  <h1 class="text-3xl text-gray-900 font-semibold tracking-wide uppercase mb-2">
    Transaction Details
  </h1>
  <a
    class="text-sm break-all hover:underline"
    href="https://explorer.cardano-testnet.iohkdev.io/en/transaction?id={{ transaction.tx_id }}"
    target="_blank"
    rel="noopener"
  >
    <i class="fas fa-link"></i> {{ transaction.tx_id }}
  </a>

{% endblock %}

{% block content %}
  <div class="py-6 text-xs break-all">
    <pre>{{ transaction.tx_info }}</pre>
  </div>
{% endblock %}

app/templates/core/wallet_detail.html
{% extends 'base.html' %}
{% load static %}
{% load core_extras %}

{% block style %}
    {{ block.super }}

    <style>
    #transfer-ada-form label:not(:first-of-type) {
        margin-top: 1.2rem;
    }

    .errorlist li {
      color: red;
      font-size: 0.875rem;
    }

    .errorlist.nonfield {
      order: 1;
      margin-top: 0.5rem;
    }

    #id_address {
        font-size: 0.875rem;
    }

    .utxo-cell {
      border-top: 1px solid rgb(194, 194, 194);
      font-size: 0.825rem;
      padding: 0.5rem;
      vertical-align: top;
    }
    </style>
{% endblock %}

{% block header_content %}
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between">
    <div class="flex items-center">
      <i class="fas fa-wallet text-8xl text-green-700 mr-4"></i>
      <div>
        <h1 class="text-3xl text-gray-900 font-semibold tracking-wide">
          {{ wallet.name }}
        </h1>
        <p class="text-base text-gray-900">
          ₳ {{ wallet.lovelace_balance|toada|floatformat:6 }}
        </p>
      </div>
    </div>

    <form
      action="{{ request.path }}consolidate/"
      id="consolidate-utxos-form"
      method="post"
      class="mt-4 sm:mt-0 sm:mx-4"
    >
      {% csrf_token %}
      {{ consolidate_tokens_form }}
      <button
        type="submit"
        class="
          rounded-md border border-transparent shadow-sm
          px-4 py-2 w-full
          bg-green-700 hover:bg-green-800
          focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-800
          text-base font-medium text-white
        ">
        Consolidate UTxOs
      </button>
    </form>
  </div>
{% endblock %}

{% block content %}
  <main>
    <div class="flex flex-col lg:flex-row">
      <div class="flex-grow mt-4">
        <table class="utxo-table w-full">
          <thead>
            <tr>
              <th class="text-left p-2">Tx Hash</th>
              <th class="p-2 w-14">Tx Ix</th>
              <th class="p-2 w-28">Value</th>
            </tr>
          </thead>
          <tbody>
            {% for utxo in wallet.lovelace_utxos %}
              <tr>
                <td class="utxo-cell">
                  <a
                    class="break-all font-mono hover:underline"
                    href="https://explorer.cardano-testnet.iohkdev.io/en/transaction?id={{ utxo.TxHash }}"
                    target="_blank"
                    rel="noopener"
                  >
                    {{ utxo.TxHash }}
                  </a>
                </td>
                <td class="utxo-cell text-center">
                  {{ utxo.TxIx }}
                </td>
                <td class="utxo-cell text-center">
                  {{ utxo.Tokens|token_list|safe }}
                </td>
              </tr>
            {% empty %}
              <tr>
                <td
                  class="text-center bg-gray-50 rounded-md p-2"
                  colspan="3"
                >
                  <i class="fas fa-info-circle mr-2"></i> No ADA UTxOs
                </td>
              </tr>
            {% endfor %}
          </tbody>

          <tbody>
            <tr>
              <td colspan="3" class="py-8">
                <hr class="border-2 border-green-700" />
              </td>
            </tr>
          </tbody>
          <tbody>
          {% for utxo in wallet.token_utxos %}
            <tr>
              <td class="utxo-cell">
                <a
                  class="break-all font-mono text-left hover:underline"
                  href="https://explorer.cardano-testnet.iohkdev.io/en/transaction?id={{ utxo.TxHash }}"
                  target="_blank"
                  rel="noopener"
                >
                  {{ utxo.TxHash }}
                </a>
              </td>
              <td class="utxo-cell text-center">
                {{ utxo.TxIx }}
              </td>
              <td class="utxo-cell text-center">
                {{ utxo.Tokens|token_list|safe }}
              </td>
            </tr>
          {% empty %}
            <tr>
              <td
                class="text-center bg-gray-50 rounded-md p-2"
                colspan="3"
              >
                <i class="fas fa-info-circle mr-2"></i> No multi-asset UTxOs
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>

      <div
        class="
        rounded-md bg-gray-100 my-8 p-4
        lg:w-72 lg:ml-3 lg:my-4
      ">
        {% include 'core/include/transfer_ada_form.html' %}
      </div>
    </div>
  </main>
{% endblock %}

{% block body_scripts %}
  {{ block.super }}

  <script>
    var walletId = "{{ wallet.id }}";
  </script>

  <script src="{% static 'js/wallet_detail.js' %}"></script>
{% endblock %}

app/templates/core/wallet_list.html
{% extends 'base.html' %}
{% load static %}

{% block header_content %}
  <h1 class="text-3xl text-gray-900 font-semibold tracking-wide uppercase">
    Wallets
  </h1>
{% endblock %}


{% block content %}
  <div class="py-8">
    <ul class="space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-8 md:gap-y-10">
    {% for wallet in wallet_list %}
      <li class="flex">
        <div class="mr-5">
          <a
            class="text-green-700 hover:text-green-800"
            href="{% url 'wallet.read' wallet.id %}"
          >
            <i class="fas fa-wallet text-8xl"></i>
          </a>
          <p class="text-sm text-gray-500 text-center">
            ₳ {{ wallet.ada_balance|floatformat:6 }}
          </p>
        </div>

        <div>
          <h2 class="text-xl leading-6 font-medium text-gray-900 mb-2">
            <a href="{% url 'wallet.read' wallet.id %}">
              {{ wallet.name }}
            </a>
          </h2>
          <p class="text-sm text-gray-500 break-all font-mono">
            {{ wallet.payment_address }}
          </p>
        </div>
      </li>
    {% endfor %}
    </ul>
  </div>
{% endblock %}